name: OpenAI Chatbot Leveraging GPT 3.5 and GPT 4
description: |
  Leverage OpenAI for Retrieval Augmented Generation (RAG) Question-Answering Large Language Model (LLM) Bot with local documents. This AMP employs Chroma Vector DB for semantic search.

author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2023-12-12"

environment_variables:
  OPENAI_KEY:
    default: "sk-xxxx"
    description: "If this is not set now, it will need to be configured for the application to function."
    required: true

  COLLECTION_NAME:
    default: "cml-default"
    description: "Enter preferred collection name for Chroma DB to store document embeddings in."
    required: true

runtimes:
  - editor: Workbench
    kernel: Python 3.10
    edition: Standard

tasks:
  - type: run_session
    name: Install Dependencies
    script: 0_session-install-deps/install_dependencies.py
    short_summary: Install Dependencies
    kernel: python3
    cpu: 2
    memory: 8

  - type: run_session
    name: Setup Chroma Server
    script: 1_session-setup-chroma/setup_chroma.py
    short_summary: Setup Chroma Server Vector DB
    long_summary: Resolve sqlite dependency with python version and control logging in Chroma server package
    kernel: python3
    cpu: 1
    memory: 2
 
  - type: create_job
    name: Populate Vector DB with documents embeddings
    entity_label: vectordb_insert
    script: 3_job-populate-vectordb/populate_vectors.py
    arguments: None
    short_summary: Create job to populate Vector Database with document embeddings. 
    long_summary: Create job to launch Milvus Vector Database locally and insert embeddings for documents. Embeddings are generated by the locally running embeddings model.
    cpu: 1
    memory: 4
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: run_job
    entity_label: vectordb_insert
    short_summary: Populate Vector DB with documents embeddings
  
  - type: start_application
    name: CML OpenAI Chatbot
    subdomain: cmlllm
    script: 4_app/llm_rag_app.py
    short_summary: Start CML OpenAI Chatbot application
    long_summary: This application requires an available GPU to run the LLM model. Startup may be delayed if autoscaling is being performed or fail if GPU cannot be scheduled on this workspace. Please contact your administrator for GPU scheduling.
    cpu: 2
    memory: 8
    environment_variables:
      TASK_TYPE: START_APPLICATION
